swagger: "2.0"
info:
  description: "API for current cases and more stuff about COVID-19"
  title: Covid-19 current cases
host: corona.lmao.ninja
basePath: /
schemes:
  - https
paths:
   /v2/all:
    get:
      operationId: allCases
      summary: All cases
      produces:
        - application/json
      responses:
         200:
           description: OK
   /v2/countries:
    get:
      operationId: casesByCountries
      summary: Cases By Countries
      produces:
        - application/json
      responses:
         200:
           description: OK
   /v2/countries/{country-name}:
    get:
      operationId: casesInCountry
      summary: Cases In Country
      produces:
        - application/json
      parameters:
        - name: country-name
          in: path
          type: string
          required: true
          default: "Italy"
      responses:
         200:
           description: OK
   /v2/states:
    get:
      operationId: casesInUSA
      summary: Cases In USA
      produces:
        - application/json
      responses:
         200:
           description: OK
definitions: []
