name: Grok Connect
on:
  workflow_dispatch: {}
  push:
    paths:
      - 'connectors/grok_connect/**'
jobs:
  check_grok_connnect:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true package
      - name: Get version
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=version::$VERSION"
      - name: Scan Grok Connect JAR
        uses: anchore/scan-action@v3
        with:
          path: "connectors/grok_connect/target/grok_conect-${{ steps.get_version.outputs.version }}.jar"
          fail-build: true
          severity-cutoff: critical

  check_grok_connnect_libraries:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan Grok Connect Libraries
        uses: anchore/scan-action@v3
        with:
          path: "connectors/grok_connect/lib"
          fail-build: true
          severity-cutoff: critical
