name: Grok Connect
on:
  workflow_dispatch: {}
  push:
    paths:
      - 'connectors/**'
jobs:
  vulnerability_scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan Grok Connect
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "connectors/"
          fail-build: false
          severity-cutoff: critical
          acs-report-enable: true
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        working-directory: ./connectors
        run: mvn -Dmaven.test.skip=true package
