name: JS API Package
on:
  push:
    branches:
      - 'master'
    paths:
      - 'js-api/package.json'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
        working-directory: ./js-api
      - run: npm run build
        working-directory: ./js-api
      - run: npm run build-ts
        working-directory: ./js-api
      - run: npm publish
        working-directory: ./js-api
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Commit package-lock.json
        run: |
          if [ ! -z "$(git status -s js-api/package-lock.json)" ]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'githubactions@datagrok.ai'
            git add ${{ matrix.project }}/package-lock.json
            git commit -m "GitHub Actions: Update js-api/package-lock.json "
            git push
          fi
